// CRM 목 데이터. 고객·주문·대기열·과거 상담 이력은 아직 연동할 백엔드가 없어 여기서 만듭니다.
// 날짜는 앱을 처음 연 날을 기준으로 상대값으로 만들어 반품 기한 등이 항상 같은 상황이 되게 합니다.
import { isoDaysAgo } from "./format";
import type { CrmState, Customer, HistoryRecord, Order, QueueItem } from "./types";

export const STATE_VERSION = 1;

function orderNo(iso: string, seq: string) {
  const d = new Date(iso);
  const ymd = `${d.getFullYear()}${String(d.getMonth() + 1).padStart(2, "0")}${String(d.getDate()).padStart(2, "0")}`;
  return `${ymd}-${seq}`;
}

export function createSeed(now = new Date()): CrmState {
  const ago = (days: number, h = 14, m = 0) => isoDaysAgo(days, h, m, now);

  const customers: Customer[] = [
    {
      id: "C-10231",
      name: "박서연",
      gender: "여",
      age: 34,
      birth: "920314",
      phone: "010-5812-2214",
      email: "sy.park@example.com",
      grade: "GOLD",
      since: "2021-03-14T09:00:00.000Z",
      orderCount: 47,
      ltv: 3284000,
      tags: ["사이즈 민감", "재구매 높음", "앱 주문"],
      address: "서울 마포구 월드컵북로 402 (상암동) 1203호",
      addressShort: "서울 마포구 상암동",
      payMethods: ["현대카드 1127 (기본)", "카카오페이"],
    },
    {
      id: "C-20417",
      name: "이도윤",
      gender: "남",
      age: 38,
      birth: "880702",
      phone: "010-3391-8830",
      email: "doyoon.lee@example.com",
      grade: "SILVER",
      since: "2022-07-02T09:00:00.000Z",
      orderCount: 18,
      ltv: 912000,
      tags: ["주방용품", "PC 주문"],
      address: "경기 성남시 분당구 판교역로 235 (삼평동) 704호",
      addressShort: "경기 성남시 분당구",
      payMethods: ["신한카드 5530 (기본)"],
    },
    {
      id: "C-00982",
      name: "정하은",
      gender: "여",
      age: 41,
      birth: "850921",
      phone: "010-7720-1402",
      email: "haeun.j@example.com",
      grade: "VIP",
      since: "2019-11-20T09:00:00.000Z",
      orderCount: 126,
      ltv: 12840000,
      tags: ["VIP", "선물 포장 자주 이용"],
      caution: "최근 30일 불만 상담 1건 (포장 파손)",
      address: "서울 강남구 테헤란로 152 (역삼동) 2201호",
      addressShort: "서울 강남구 역삼동",
      payMethods: ["삼성카드 8841 (기본)", "네이버페이"],
    },
    {
      id: "C-31175",
      name: "최민준",
      gender: "남",
      age: 31,
      birth: "950130",
      phone: "010-2254-5567",
      email: "minjun.c@example.com",
      grade: "BASIC",
      since: "2024-01-30T09:00:00.000Z",
      orderCount: 5,
      ltv: 386000,
      tags: ["가전"],
      address: "부산 해운대구 센텀중앙로 79 (우동) 1502호",
      addressShort: "부산 해운대구 우동",
      payMethods: ["국민카드 2290 (기본)"],
    },
    {
      id: "C-18820",
      name: "한지우",
      gender: "여",
      age: 27,
      birth: "990517",
      phone: "010-6618-9021",
      email: "jiwoo.han@example.com",
      grade: "GOLD",
      since: "2020-05-17T09:00:00.000Z",
      orderCount: 39,
      ltv: 2107000,
      tags: ["색상 교환 이력", "앱 주문"],
      address: "대구 수성구 동대구로 120 (범어동) 901호",
      addressShort: "대구 수성구 범어동",
      payMethods: ["토스페이", "현대카드 3312"],
    },
  ];

  const orders: Order[] = [
    // 박서연 — 문의 유형별로 관련 주문이 하나씩 있도록 구성
    {
      no: orderNo(ago(9), "004521"),
      customerId: "C-10231",
      orderedAt: ago(9, 13, 58),
      item: "린넨 셔츠 원피스",
      option: "베이지 / M",
      qty: 1,
      price: 89000,
      payMethod: "현대카드 1127 일시불",
      approvalNo: "30918442",
      status: "배송 완료",
      carrier: "CJ대한통운",
      invoice: "6892-0012-4471",
      shippedAt: ago(8, 16),
      deliveredAt: ago(6, 11, 20),
      tracking: [
        { title: "배송 완료", at: ago(6, 11, 20), desc: "문 앞 전달" },
        { title: "배송 출발", at: ago(6, 7, 40), desc: "마포 상암 대리점" },
        { title: "간선 상차", at: ago(7, 22, 10), desc: "곤지암 허브" },
        { title: "집화 완료", at: ago(8, 16), desc: "파주 물류센터" },
      ],
    },
    {
      no: orderNo(ago(7), "011873"),
      customerId: "C-10231",
      orderedAt: ago(7, 20, 31),
      item: "쿠션 러닝화",
      option: "화이트 / 240",
      qty: 1,
      price: 79000,
      payMethod: "카카오페이",
      approvalNo: "KP-77120938",
      status: "배송 중",
      carrier: "롯데택배",
      invoice: "2471-8830-1102",
      shippedAt: ago(5, 15),
      tracking: [
        { title: "간선 하차", at: ago(4, 3, 12), desc: "곤지암 허브 · 이후 갱신 없음" },
        { title: "집화 완료", at: ago(5, 15), desc: "이천 물류센터" },
      ],
    },
    {
      no: orderNo(ago(0), "020114"),
      customerId: "C-10231",
      orderedAt: ago(0, 9, 12),
      item: "무선 이어폰 케이스",
      option: "라벤더",
      qty: 1,
      price: 19000,
      payMethod: "현대카드 1127 일시불",
      approvalNo: "30929017",
      status: "결제 완료",
    },
    {
      no: orderNo(ago(27), "118903"),
      customerId: "C-10231",
      orderedAt: ago(27, 10, 5),
      item: "코튼 와이드 팬츠",
      option: "아이보리 / 27",
      qty: 1,
      price: 49000,
      payMethod: "현대카드 1127 일시불",
      approvalNo: "30902291",
      status: "구매 확정",
      carrier: "CJ대한통운",
      invoice: "6892-0009-1180",
      shippedAt: ago(26, 16),
      deliveredAt: ago(24, 12),
    },
    // 이도윤
    {
      no: orderNo(ago(8), "007731"),
      customerId: "C-20417",
      orderedAt: ago(8, 21, 2),
      item: "스테인리스 텀블러 500ml",
      option: "매트 블랙",
      qty: 2,
      price: 38000,
      payMethod: "신한카드 5530 일시불",
      approvalNo: "55201874",
      status: "배송 중",
      carrier: "한진택배",
      invoice: "5120-3381-7720",
      shippedAt: ago(6, 14),
      tracking: [
        { title: "배송 출발 전", at: ago(5, 9), desc: "성남 터미널 · 이후 갱신 없음" },
        { title: "집화 완료", at: ago(6, 14), desc: "용인 물류센터" },
      ],
    },
    {
      no: orderNo(ago(5), "009912"),
      customerId: "C-20417",
      orderedAt: ago(5, 11, 40),
      item: "블루투스 스피커",
      option: "샌드 베이지",
      qty: 1,
      price: 129000,
      payMethod: "신한카드 5530 3개월",
      approvalNo: "55209931",
      status: "배송 완료",
      carrier: "CJ대한통운",
      invoice: "6892-0015-3302",
      shippedAt: ago(4, 15),
      deliveredAt: ago(3, 10, 30),
    },
    // 정하은
    {
      no: orderNo(ago(15), "002210"),
      customerId: "C-00982",
      orderedAt: ago(15, 19, 22),
      item: "캐시미어 머플러",
      option: "카멜 / 선물 포장",
      qty: 1,
      price: 159000,
      payMethod: "삼성카드 8841 일시불",
      approvalNo: "88412203",
      status: "배송 완료",
      carrier: "CJ대한통운",
      invoice: "6892-0007-4410",
      shippedAt: ago(14, 16),
      deliveredAt: ago(12, 13),
    },
    {
      no: orderNo(ago(1), "015530"),
      customerId: "C-00982",
      orderedAt: ago(1, 22, 47),
      item: "가죽 카드지갑",
      option: "버건디",
      qty: 1,
      price: 68000,
      payMethod: "삼성카드 8841 일시불",
      approvalNo: "88419022",
      status: "결제 완료",
    },
    // 최민준
    {
      no: orderNo(ago(74), "003345"),
      customerId: "C-31175",
      orderedAt: ago(74, 10),
      item: "초고속 블렌더",
      option: "1.5L / 그레이",
      qty: 1,
      price: 189000,
      payMethod: "국민카드 2290 일시불",
      approvalNo: "22908813",
      status: "구매 확정",
      carrier: "CJ대한통운",
      invoice: "6892-0001-9021",
      shippedAt: ago(73, 15),
      deliveredAt: ago(71, 12),
    },
    // 한지우
    {
      no: orderNo(ago(4), "012287"),
      customerId: "C-18820",
      orderedAt: ago(4, 8, 55),
      item: "오버핏 후드티",
      option: "그레이 / L",
      qty: 1,
      price: 59000,
      payMethod: "토스페이",
      approvalNo: "TS-40211873",
      status: "배송 완료",
      carrier: "CJ대한통운",
      invoice: "6892-0016-0081",
      shippedAt: ago(3, 16),
      deliveredAt: ago(2, 14, 10),
    },
  ];

  const queue: QueueItem[] = [
    { id: "Q-2291", customerId: "C-10231", waitSeconds: 134, urgency: "high", arsMenu: "주문·배송 문의" },
    { id: "Q-2292", customerId: "C-20417", waitSeconds: 112, urgency: "mid", arsMenu: "배송 조회" },
    { id: "Q-2293", customerId: "C-00982", waitSeconds: 91, urgency: "mid", arsMenu: "결제·환불" },
    { id: "Q-2294", customerId: "C-31175", waitSeconds: 70, urgency: "low", arsMenu: "상품·AS" },
    { id: "Q-2295", customerId: "C-18820", waitSeconds: 48, urgency: "low", arsMenu: "교환·반품" },
  ];

  const history: HistoryRecord[] = [
    seedRecord({
      id: "H-0820-1",
      customerId: "C-10231",
      startedAt: ago(34, 15, 12),
      durationSec: 402,
      agent: "이수민",
      category: "refund_exchange",
      tags: ["사이즈 불만", "배송비 문의"],
      summary: {
        request: "니트 가디건(차콜/FREE) 사이즈가 커서 반품을 요청했습니다.",
        told: "단순 변심 반품은 왕복 배송비 6,000원이 고객 부담이라고 안내했습니다.",
        result: "반품 회수 접수를 완료했습니다 (RT-41022). 검수 후 63,000원 환불 예정입니다.",
      },
      actions: [
        { id: "A-seed-1", actionId: "return_pickup", label: "반품 회수 접수", receiptNo: "RT-41022", at: ago(34, 15, 18) },
      ],
    }),
    seedRecord({
      id: "H-0511-1",
      customerId: "C-10231",
      startedAt: ago(140, 11, 3),
      durationSec: 215,
      agent: "김하늘",
      category: "shipping",
      tags: ["출고 지연"],
      summary: {
        request: "주문 후 3일째 출고되지 않은 이유를 문의했습니다.",
        told: "물류센터 입고 지연으로 다음 날 출고 예정이라고 안내했습니다.",
        result: "다음 날 출고를 확인하고 문자로 안내했습니다.",
      },
      actions: [],
    }),
    seedRecord({
      id: "H-0730-2",
      customerId: "C-20417",
      startedAt: ago(61, 10, 44),
      durationSec: 188,
      agent: "정유진",
      category: "product_inquiry",
      tags: ["사용 방법"],
      summary: {
        request: "텀블러 뚜껑 분리 세척 방법을 문의했습니다.",
        told: "상품 상세의 세척 가이드와 식기세척기 사용 불가 사항을 안내했습니다.",
        result: "추가 처리 없이 상담을 마쳤습니다.",
      },
      actions: [],
    }),
    seedRecord({
      id: "H-0909-3",
      customerId: "C-00982",
      startedAt: ago(20, 16, 20),
      durationSec: 544,
      agent: "이수민",
      category: "complaint",
      tags: ["포장 파손", "VIP"],
      summary: {
        request: "선물 포장 상자가 찌그러진 채 도착해 불만을 제기했습니다.",
        told: "불편에 사과하고 포장 개선 VOC 등록과 처리 절차를 안내했습니다.",
        result: "VOC를 등록하고 (VOC-30412) 적립금 보상을 물류팀에 이관했습니다.",
      },
      actions: [
        { id: "A-seed-2", actionId: "voc", label: "VOC 등록", receiptNo: "VOC-30412", at: ago(20, 16, 27) },
        { id: "A-seed-3", actionId: "transfer", label: "담당자 이관", receiptNo: "TR-18830", at: ago(20, 16, 29), detail: "물류팀" },
      ],
    }),
    seedRecord({
      id: "H-0701-4",
      customerId: "C-18820",
      startedAt: ago(90, 13, 50),
      durationSec: 320,
      agent: "김하늘",
      category: "refund_exchange",
      tags: ["색상 교환"],
      summary: {
        request: "니트 원피스 색상을 네이비로 교환하고 싶다고 요청했습니다.",
        told: "교환 왕복 배송비 6,000원이 고객 부담이라고 안내했습니다.",
        result: "교환 접수를 완료했습니다 (EX-22019).",
      },
      actions: [
        { id: "A-seed-4", actionId: "exchange", label: "교환 접수", receiptNo: "EX-22019", at: ago(90, 13, 58) },
      ],
    }),
  ];

  return {
    version: STATE_VERSION,
    agent: { name: "김하늘", role: "상담사 · 커머스 1팀", handledToday: 23, target: 30 },
    agentStatus: "available",
    customers: Object.fromEntries(customers.map((c) => [c.id, c])),
    orders,
    queue,
    history,
  };
}

function seedRecord(
  r: Pick<HistoryRecord, "id" | "customerId" | "startedAt" | "durationSec" | "agent" | "category" | "tags" | "summary" | "actions">,
): HistoryRecord {
  return {
    ...r,
    categorySource: "agent",
    verified: true,
    editedFields: [],
    notices: [],
    memo: "",
    transcripts: [],
    followups: [],
    seed: true,
  };
}
