// AX CRM 아이콘(307개, 약 600KB) 중 src에서 실제로 쓰는 아이콘만 추려
// src/design-system/icons/icon-data.js 와 Icon.d.ts 의 IconName 을 다시 만듭니다.
//
// 사용법: node scripts/subset-icons.mjs "<AX CRM Design System>/components/icons/icon-data.js"
// 새 아이콘 이름을 코드에 추가했다면 이 스크립트를 다시 실행하세요.
import { copyFileSync, mkdtempSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, relative } from "node:path";
import { pathToFileURL } from "node:url";

const source = process.argv[2];
if (!source) {
  console.error("원본 icon-data.js 경로를 인자로 넘기세요.");
  process.exit(1);
}

const root = new URL("..", import.meta.url).pathname;
const iconsDir = join(root, "src/design-system/icons");

// 원본은 ESM(export default)이라 .mjs로 복사해 불러옵니다.
const tmp = join(mkdtempSync(join(tmpdir(), "icons-")), "icon-data.mjs");
copyFileSync(source, tmp);
const { default: all } = await import(pathToFileURL(tmp).href);

function walk(dir, out = []) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p, out);
    else if (/\.(tsx?|jsx?)$/.test(name) && !p.startsWith(iconsDir)) out.push(p);
  }
  return out;
}

const used = new Set();
for (const file of walk(join(root, "src"))) {
  const text = readFileSync(file, "utf8");
  for (const m of text.matchAll(/["'`]([A-Z][A-Za-z0-9]+)["'`]/g)) {
    if (all[m[1]]) used.add(m[1]);
  }
}

const names = [...used].sort();
const body = names.map((n) => `  ${JSON.stringify(n)}: ${JSON.stringify(all[n])},`).join("\n");
writeFileSync(
  join(iconsDir, "icon-data.js"),
  `// Generated by scripts/subset-icons.mjs from AX CRM Design System/components/icons/icon-data.js\n` +
    `// ${names.length} of ${Object.keys(all).length} icons — only names referenced in src/.\n` +
    `export default {\n${body}\n};\n`,
);

const dts = readFileSync(join(iconsDir, "Icon.d.ts"), "utf8");
const union = `export type IconName =\n${names.map((n) => `  | ${JSON.stringify(n)}`).join("\n")};`;
writeFileSync(join(iconsDir, "Icon.d.ts"), dts.replace(/export type IconName =[\s\S]*?;/, union));

console.log(`${names.length}개 아이콘을 ${relative(root, iconsDir)}에 썼습니다.`);
